version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongoDB
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: TasksDB
  
  spring_app:
    container_name: springApp
    build: ./
    ports:
      - '8090:8090'
    depends_on:
      - mongo